---
- name: opendkim packages are installed
  apt: pkg={{ item }} state=installed
  with_items:
   - opendkim
   - opendkim-tools

- name: opendkim socket configured
  lineinfile: dest=/etc/default/opendkim regexp=^SOCKET= line='SOCKET="inet:12301@localhost"'


- name: opendkim directory present
  file: path=/etc/opendkim state=directory
  file: path=/etc/opendkim/keys state=directory

- name: opendkim TrustedHosts present
  copy: src=TrustedHosts dest=/etc/opendkim/TrustedHosts


- name: opendkim is configured
  template: src=opendkim.conf.j2 dest=/etc/opendkim.conf


- name: opendkim KeyTable is configured
  template: src=KeyTable.j2 dest=/etc/opendkim/KeyTable


- name: opendkim SigningTable is configured
  template: src=SigningTable.j2 dest=/etc/opendkim/SigningTable


- name: ensure signing key is present
  file: path=/etc/opendkim/keys/{{ item.key }} owner=opendkim group=opendkim
  with_items: "{{ dkim_domains }}"


- name: chown and chmod /etc/opendkim
  file: path=/etc/opendkim state=directory owner=opendkim group=opendkim recurse=yes


