---
- name: postfix is installed
  apt: pkg=postfix state=installed
  tags: postfix

- name: postfix mynetworks is configured
  lineinfile: dest=/etc/postfix/main.cf regexp=^mynetworks line="mynetworks = {{ postfix_mynetworks }}"

- name: postfix milter_protocol is configured
  lineinfile: dest=/etc/postfix/main.cf regexp=^milter_protocol line="milter_protocol = 2"


- name: postfix milter_default_action is configured
  lineinfile: dest=/etc/postfix/main.cf regexp=^milter_default_action line="milter_default_action = accept"


- name: postfix smtpd_milters is configured
  lineinfile: dest=/etc/postfix/main.cf regexp=^smtpd_milters line="smtpd_milters = {{ postfix_milters }}"


- name: postfix non_smtpd_milters is configured
  lineinfile: dest=/etc/postfix/main.cf regexp=^non_smtpd_milters line="non_smtpd_milters = {{ postfix_milters }}"

